! Author:  Philipp Engel
! Licence: ISC
module sdl3_keycode
    !! Auto-generated Fortran 2023 interface bindings to `SDL3/SDL_keycode.h`.
    use :: sdl3_stdinc
    implicit none (type, external)
    private

    integer, parameter, public :: sdl_keycode = uint32 !! SDL_Keycode
    integer, parameter, public :: sdl_keymod  = uint16 !! SDL_Keymod

    integer(c_unsigned), parameter, public :: SDLK_EXTENDED_MASK = shiftl(1_c_unsigned, 29)
    integer(c_unsigned), parameter, public :: SDLK_SCANCODE_MASK = shiftl(1_c_unsigned, 30)
    ! integer(c_unsigned), parameter, public :: SDL_SCANCODE_TO_KEYCODE(X)  (X | SDLK_SCANCODE_MASK)

    integer(c_unsigned), parameter, public :: SDLK_UNKNOWN                = int(z'00000000', c_unsigned) ! 0
    integer(c_unsigned), parameter, public :: SDLK_RETURN                 = int(z'0000000d', c_unsigned) ! `\r`
    integer(c_unsigned), parameter, public :: SDLK_ESCAPE                 = int(z'0000001b', c_unsigned) ! `\x1B`
    integer(c_unsigned), parameter, public :: SDLK_BACKSPACE              = int(z'00000008', c_unsigned) ! `\b`
    integer(c_unsigned), parameter, public :: SDLK_TAB                    = int(z'00000009', c_unsigned) ! `\t`
    integer(c_unsigned), parameter, public :: SDLK_SPACE                  = int(z'00000020', c_unsigned) ! ` `
    integer(c_unsigned), parameter, public :: SDLK_EXCLAIM                = int(z'00000021', c_unsigned) ! `!`
    integer(c_unsigned), parameter, public :: SDLK_DBLAPOSTROPHE          = int(z'00000022', c_unsigned) ! `"`
    integer(c_unsigned), parameter, public :: SDLK_HASH                   = int(z'00000023', c_unsigned) ! `#`
    integer(c_unsigned), parameter, public :: SDLK_DOLLAR                 = int(z'00000024', c_unsigned) ! `$`
    integer(c_unsigned), parameter, public :: SDLK_PERCENT                = int(z'00000025', c_unsigned) ! `%`
    integer(c_unsigned), parameter, public :: SDLK_AMPERSAND              = int(z'00000026', c_unsigned) ! `&`
    integer(c_unsigned), parameter, public :: SDLK_APOSTROPHE             = int(z'00000027', c_unsigned) ! `\'`
    integer(c_unsigned), parameter, public :: SDLK_LEFTPAREN              = int(z'00000028', c_unsigned) ! `(`
    integer(c_unsigned), parameter, public :: SDLK_RIGHTPAREN             = int(z'00000029', c_unsigned) ! `)`
    integer(c_unsigned), parameter, public :: SDLK_ASTERISK               = int(z'0000002a', c_unsigned) ! `*`
    integer(c_unsigned), parameter, public :: SDLK_PLUS                   = int(z'0000002b', c_unsigned) ! `+`
    integer(c_unsigned), parameter, public :: SDLK_COMMA                  = int(z'0000002c', c_unsigned) ! `,`
    integer(c_unsigned), parameter, public :: SDLK_MINUS                  = int(z'0000002d', c_unsigned) ! `-`
    integer(c_unsigned), parameter, public :: SDLK_PERIOD                 = int(z'0000002e', c_unsigned) ! `.`
    integer(c_unsigned), parameter, public :: SDLK_SLASH                  = int(z'0000002f', c_unsigned) ! `/`
    integer(c_unsigned), parameter, public :: SDLK_0                      = int(z'00000030', c_unsigned) ! `0`
    integer(c_unsigned), parameter, public :: SDLK_1                      = int(z'00000031', c_unsigned) ! `1`
    integer(c_unsigned), parameter, public :: SDLK_2                      = int(z'00000032', c_unsigned) ! `2`
    integer(c_unsigned), parameter, public :: SDLK_3                      = int(z'00000033', c_unsigned) ! `3`
    integer(c_unsigned), parameter, public :: SDLK_4                      = int(z'00000034', c_unsigned) ! `4`
    integer(c_unsigned), parameter, public :: SDLK_5                      = int(z'00000035', c_unsigned) ! `5`
    integer(c_unsigned), parameter, public :: SDLK_6                      = int(z'00000036', c_unsigned) ! `6`
    integer(c_unsigned), parameter, public :: SDLK_7                      = int(z'00000037', c_unsigned) ! `7`
    integer(c_unsigned), parameter, public :: SDLK_8                      = int(z'00000038', c_unsigned) ! `8`
    integer(c_unsigned), parameter, public :: SDLK_9                      = int(z'00000039', c_unsigned) ! `9`
    integer(c_unsigned), parameter, public :: SDLK_COLON                  = int(z'0000003a', c_unsigned) ! `:`
    integer(c_unsigned), parameter, public :: SDLK_SEMICOLON              = int(z'0000003b', c_unsigned) ! `;`
    integer(c_unsigned), parameter, public :: SDLK_LESS                   = int(z'0000003c', c_unsigned) ! `<`
    integer(c_unsigned), parameter, public :: SDLK_EQUALS                 = int(z'0000003d', c_unsigned) ! `=`
    integer(c_unsigned), parameter, public :: SDLK_GREATER                = int(z'0000003e', c_unsigned) ! `>`
    integer(c_unsigned), parameter, public :: SDLK_QUESTION               = int(z'0000003f', c_unsigned) ! `?`
    integer(c_unsigned), parameter, public :: SDLK_AT                     = int(z'00000040', c_unsigned) ! `@`
    integer(c_unsigned), parameter, public :: SDLK_LEFTBRACKET            = int(z'0000005b', c_unsigned) ! `[`
    integer(c_unsigned), parameter, public :: SDLK_BACKSLASH              = int(z'0000005c', c_unsigned) ! `\\`
    integer(c_unsigned), parameter, public :: SDLK_RIGHTBRACKET           = int(z'0000005d', c_unsigned) ! `]`
    integer(c_unsigned), parameter, public :: SDLK_CARET                  = int(z'0000005e', c_unsigned) ! `^`
    integer(c_unsigned), parameter, public :: SDLK_UNDERSCORE             = int(z'0000005f', c_unsigned) ! `_`
    integer(c_unsigned), parameter, public :: SDLK_GRAVE                  = int(z'00000060', c_unsigned) ! ```
    integer(c_unsigned), parameter, public :: SDLK_A                      = int(z'00000061', c_unsigned) ! `a`
    integer(c_unsigned), parameter, public :: SDLK_B                      = int(z'00000062', c_unsigned) ! `b`
    integer(c_unsigned), parameter, public :: SDLK_C                      = int(z'00000063', c_unsigned) ! `c`
    integer(c_unsigned), parameter, public :: SDLK_D                      = int(z'00000064', c_unsigned) ! `d`
    integer(c_unsigned), parameter, public :: SDLK_E                      = int(z'00000065', c_unsigned) ! `e`
    integer(c_unsigned), parameter, public :: SDLK_F                      = int(z'00000066', c_unsigned) ! `f`
    integer(c_unsigned), parameter, public :: SDLK_G                      = int(z'00000067', c_unsigned) ! `g`
    integer(c_unsigned), parameter, public :: SDLK_H                      = int(z'00000068', c_unsigned) ! `h`
    integer(c_unsigned), parameter, public :: SDLK_I                      = int(z'00000069', c_unsigned) ! `i`
    integer(c_unsigned), parameter, public :: SDLK_J                      = int(z'0000006a', c_unsigned) ! `j`
    integer(c_unsigned), parameter, public :: SDLK_K                      = int(z'0000006b', c_unsigned) ! `k`
    integer(c_unsigned), parameter, public :: SDLK_L                      = int(z'0000006c', c_unsigned) ! `l`
    integer(c_unsigned), parameter, public :: SDLK_M                      = int(z'0000006d', c_unsigned) ! `m`
    integer(c_unsigned), parameter, public :: SDLK_N                      = int(z'0000006e', c_unsigned) ! `n`
    integer(c_unsigned), parameter, public :: SDLK_O                      = int(z'0000006f', c_unsigned) ! `o`
    integer(c_unsigned), parameter, public :: SDLK_P                      = int(z'00000070', c_unsigned) ! `p`
    integer(c_unsigned), parameter, public :: SDLK_Q                      = int(z'00000071', c_unsigned) ! `q`
    integer(c_unsigned), parameter, public :: SDLK_R                      = int(z'00000072', c_unsigned) ! `r`
    integer(c_unsigned), parameter, public :: SDLK_S                      = int(z'00000073', c_unsigned) ! `s`
    integer(c_unsigned), parameter, public :: SDLK_T                      = int(z'00000074', c_unsigned) ! `t`
    integer(c_unsigned), parameter, public :: SDLK_U                      = int(z'00000075', c_unsigned) ! `u`
    integer(c_unsigned), parameter, public :: SDLK_V                      = int(z'00000076', c_unsigned) ! `v`
    integer(c_unsigned), parameter, public :: SDLK_W                      = int(z'00000077', c_unsigned) ! `w`
    integer(c_unsigned), parameter, public :: SDLK_X                      = int(z'00000078', c_unsigned) ! `x`
    integer(c_unsigned), parameter, public :: SDLK_Y                      = int(z'00000079', c_unsigned) ! `y`
    integer(c_unsigned), parameter, public :: SDLK_Z                      = int(z'0000007a', c_unsigned) ! `z`
    integer(c_unsigned), parameter, public :: SDLK_LEFTBRACE              = int(z'0000007b', c_unsigned) ! `{`
    integer(c_unsigned), parameter, public :: SDLK_PIPE                   = int(z'0000007c', c_unsigned) ! `|`
    integer(c_unsigned), parameter, public :: SDLK_RIGHTBRACE             = int(z'0000007d', c_unsigned) ! `}`
    integer(c_unsigned), parameter, public :: SDLK_TILDE                  = int(z'0000007e', c_unsigned) ! `~`
    integer(c_unsigned), parameter, public :: SDLK_DELETE                 = int(z'0000007f', c_unsigned) ! `\x7F`
    integer(c_unsigned), parameter, public :: SDLK_PLUSMINUS              = int(z'000000b1', c_unsigned) ! `\xB1`
    integer(c_unsigned), parameter, public :: SDLK_CAPSLOCK               = int(z'40000039', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CAPSLOCK)
    integer(c_unsigned), parameter, public :: SDLK_F1                     = int(z'4000003a', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F1)
    integer(c_unsigned), parameter, public :: SDLK_F2                     = int(z'4000003b', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F2)
    integer(c_unsigned), parameter, public :: SDLK_F3                     = int(z'4000003c', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F3)
    integer(c_unsigned), parameter, public :: SDLK_F4                     = int(z'4000003d', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F4)
    integer(c_unsigned), parameter, public :: SDLK_F5                     = int(z'4000003e', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F5)
    integer(c_unsigned), parameter, public :: SDLK_F6                     = int(z'4000003f', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F6)
    integer(c_unsigned), parameter, public :: SDLK_F7                     = int(z'40000040', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F7)
    integer(c_unsigned), parameter, public :: SDLK_F8                     = int(z'40000041', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F8)
    integer(c_unsigned), parameter, public :: SDLK_F9                     = int(z'40000042', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F9)
    integer(c_unsigned), parameter, public :: SDLK_F10                    = int(z'40000043', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F10)
    integer(c_unsigned), parameter, public :: SDLK_F11                    = int(z'40000044', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F11)
    integer(c_unsigned), parameter, public :: SDLK_F12                    = int(z'40000045', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F12)
    integer(c_unsigned), parameter, public :: SDLK_PRINTSCREEN            = int(z'40000046', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PRINTSCREEN)
    integer(c_unsigned), parameter, public :: SDLK_SCROLLLOCK             = int(z'40000047', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SCROLLLOCK)
    integer(c_unsigned), parameter, public :: SDLK_PAUSE                  = int(z'40000048', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAUSE)
    integer(c_unsigned), parameter, public :: SDLK_INSERT                 = int(z'40000049', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_INSERT)
    integer(c_unsigned), parameter, public :: SDLK_HOME                   = int(z'4000004a', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_HOME)
    integer(c_unsigned), parameter, public :: SDLK_PAGEUP                 = int(z'4000004b', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAGEUP)
    integer(c_unsigned), parameter, public :: SDLK_END                    = int(z'4000004d', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_END)
    integer(c_unsigned), parameter, public :: SDLK_PAGEDOWN               = int(z'4000004e', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAGEDOWN)
    integer(c_unsigned), parameter, public :: SDLK_RIGHT                  = int(z'4000004f', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RIGHT)
    integer(c_unsigned), parameter, public :: SDLK_LEFT                   = int(z'40000050', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LEFT)
    integer(c_unsigned), parameter, public :: SDLK_DOWN                   = int(z'40000051', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_DOWN)
    integer(c_unsigned), parameter, public :: SDLK_UP                     = int(z'40000052', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_UP)
    integer(c_unsigned), parameter, public :: SDLK_NUMLOCKCLEAR           = int(z'40000053', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_NUMLOCKCLEAR)
    integer(c_unsigned), parameter, public :: SDLK_KP_DIVIDE              = int(z'40000054', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DIVIDE)
    integer(c_unsigned), parameter, public :: SDLK_KP_MULTIPLY            = int(z'40000055', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MULTIPLY)
    integer(c_unsigned), parameter, public :: SDLK_KP_MINUS               = int(z'40000056', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MINUS)
    integer(c_unsigned), parameter, public :: SDLK_KP_PLUS                = int(z'40000057', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PLUS)
    integer(c_unsigned), parameter, public :: SDLK_KP_ENTER               = int(z'40000058', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_ENTER)
    integer(c_unsigned), parameter, public :: SDLK_KP_1                   = int(z'40000059', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_1)
    integer(c_unsigned), parameter, public :: SDLK_KP_2                   = int(z'4000005a', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_2)
    integer(c_unsigned), parameter, public :: SDLK_KP_3                   = int(z'4000005b', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_3)
    integer(c_unsigned), parameter, public :: SDLK_KP_4                   = int(z'4000005c', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_4)
    integer(c_unsigned), parameter, public :: SDLK_KP_5                   = int(z'4000005d', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_5)
    integer(c_unsigned), parameter, public :: SDLK_KP_6                   = int(z'4000005e', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_6)
    integer(c_unsigned), parameter, public :: SDLK_KP_7                   = int(z'4000005f', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_7)
    integer(c_unsigned), parameter, public :: SDLK_KP_8                   = int(z'40000060', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_8)
    integer(c_unsigned), parameter, public :: SDLK_KP_9                   = int(z'40000061', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_9)
    integer(c_unsigned), parameter, public :: SDLK_KP_0                   = int(z'40000062', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_0)
    integer(c_unsigned), parameter, public :: SDLK_KP_PERIOD              = int(z'40000063', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PERIOD)
    integer(c_unsigned), parameter, public :: SDLK_APPLICATION            = int(z'40000065', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_APPLICATION)
    integer(c_unsigned), parameter, public :: SDLK_POWER                  = int(z'40000066', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_POWER)
    integer(c_unsigned), parameter, public :: SDLK_KP_EQUALS              = int(z'40000067', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EQUALS)
    integer(c_unsigned), parameter, public :: SDLK_F13                    = int(z'40000068', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F13)
    integer(c_unsigned), parameter, public :: SDLK_F14                    = int(z'40000069', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F14)
    integer(c_unsigned), parameter, public :: SDLK_F15                    = int(z'4000006a', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F15)
    integer(c_unsigned), parameter, public :: SDLK_F16                    = int(z'4000006b', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F16)
    integer(c_unsigned), parameter, public :: SDLK_F17                    = int(z'4000006c', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F17)
    integer(c_unsigned), parameter, public :: SDLK_F18                    = int(z'4000006d', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F18)
    integer(c_unsigned), parameter, public :: SDLK_F19                    = int(z'4000006e', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F19)
    integer(c_unsigned), parameter, public :: SDLK_F20                    = int(z'4000006f', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F20)
    integer(c_unsigned), parameter, public :: SDLK_F21                    = int(z'40000070', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F21)
    integer(c_unsigned), parameter, public :: SDLK_F22                    = int(z'40000071', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F22)
    integer(c_unsigned), parameter, public :: SDLK_F23                    = int(z'40000072', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F23)
    integer(c_unsigned), parameter, public :: SDLK_F24                    = int(z'40000073', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F24)
    integer(c_unsigned), parameter, public :: SDLK_EXECUTE                = int(z'40000074', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_EXECUTE)
    integer(c_unsigned), parameter, public :: SDLK_HELP                   = int(z'40000075', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_HELP)
    integer(c_unsigned), parameter, public :: SDLK_MENU                   = int(z'40000076', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MENU)
    integer(c_unsigned), parameter, public :: SDLK_SELECT                 = int(z'40000077', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SELECT)
    integer(c_unsigned), parameter, public :: SDLK_STOP                   = int(z'40000078', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_STOP)
    integer(c_unsigned), parameter, public :: SDLK_AGAIN                  = int(z'40000079', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AGAIN)
    integer(c_unsigned), parameter, public :: SDLK_UNDO                   = int(z'4000007a', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_UNDO)
    integer(c_unsigned), parameter, public :: SDLK_CUT                    = int(z'4000007b', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CUT)
    integer(c_unsigned), parameter, public :: SDLK_COPY                   = int(z'4000007c', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_COPY)
    integer(c_unsigned), parameter, public :: SDLK_PASTE                  = int(z'4000007d', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PASTE)
    integer(c_unsigned), parameter, public :: SDLK_FIND                   = int(z'4000007e', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_FIND)
    integer(c_unsigned), parameter, public :: SDLK_MUTE                   = int(z'4000007f', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MUTE)
    integer(c_unsigned), parameter, public :: SDLK_VOLUMEUP               = int(z'40000080', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_VOLUMEUP)
    integer(c_unsigned), parameter, public :: SDLK_VOLUMEDOWN             = int(z'40000081', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_VOLUMEDOWN)
    integer(c_unsigned), parameter, public :: SDLK_KP_COMMA               = int(z'40000085', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_COMMA)
    integer(c_unsigned), parameter, public :: SDLK_KP_EQUALSAS400         = int(z'40000086', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EQUALSAS400)
    integer(c_unsigned), parameter, public :: SDLK_ALTERASE               = int(z'40000099', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_ALTERASE)
    integer(c_unsigned), parameter, public :: SDLK_SYSREQ                 = int(z'4000009a', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SYSREQ)
    integer(c_unsigned), parameter, public :: SDLK_CANCEL                 = int(z'4000009b', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CANCEL)
    integer(c_unsigned), parameter, public :: SDLK_CLEAR                  = int(z'4000009c', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CLEAR)
    integer(c_unsigned), parameter, public :: SDLK_PRIOR                  = int(z'4000009d', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PRIOR)
    integer(c_unsigned), parameter, public :: SDLK_RETURN2                = int(z'4000009e', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RETURN2)
    integer(c_unsigned), parameter, public :: SDLK_SEPARATOR              = int(z'4000009f', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SEPARATOR)
    integer(c_unsigned), parameter, public :: SDLK_OUT                    = int(z'400000a0', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_OUT)
    integer(c_unsigned), parameter, public :: SDLK_OPER                   = int(z'400000a1', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_OPER)
    integer(c_unsigned), parameter, public :: SDLK_CLEARAGAIN             = int(z'400000a2', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CLEARAGAIN)
    integer(c_unsigned), parameter, public :: SDLK_CRSEL                  = int(z'400000a3', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CRSEL)
    integer(c_unsigned), parameter, public :: SDLK_EXSEL                  = int(z'400000a4', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_EXSEL)
    integer(c_unsigned), parameter, public :: SDLK_KP_00                  = int(z'400000b0', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_00)
    integer(c_unsigned), parameter, public :: SDLK_KP_000                 = int(z'400000b1', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_000)
    integer(c_unsigned), parameter, public :: SDLK_THOUSANDSSEPARATOR     = int(z'400000b2', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_THOUSANDSSEPARATOR)
    integer(c_unsigned), parameter, public :: SDLK_DECIMALSEPARATOR       = int(z'400000b3', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_DECIMALSEPARATOR)
    integer(c_unsigned), parameter, public :: SDLK_CURRENCYUNIT           = int(z'400000b4', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CURRENCYUNIT)
    integer(c_unsigned), parameter, public :: SDLK_CURRENCYSUBUNIT        = int(z'400000b5', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CURRENCYSUBUNIT)
    integer(c_unsigned), parameter, public :: SDLK_KP_LEFTPAREN           = int(z'400000b6', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LEFTPAREN)
    integer(c_unsigned), parameter, public :: SDLK_KP_RIGHTPAREN          = int(z'400000b7', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_RIGHTPAREN)
    integer(c_unsigned), parameter, public :: SDLK_KP_LEFTBRACE           = int(z'400000b8', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LEFTBRACE)
    integer(c_unsigned), parameter, public :: SDLK_KP_RIGHTBRACE          = int(z'400000b9', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_RIGHTBRACE)
    integer(c_unsigned), parameter, public :: SDLK_KP_TAB                 = int(z'400000ba', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_TAB)
    integer(c_unsigned), parameter, public :: SDLK_KP_BACKSPACE           = int(z'400000bb', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_BACKSPACE)
    integer(c_unsigned), parameter, public :: SDLK_KP_A                   = int(z'400000bc', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_A)
    integer(c_unsigned), parameter, public :: SDLK_KP_B                   = int(z'400000bd', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_B)
    integer(c_unsigned), parameter, public :: SDLK_KP_C                   = int(z'400000be', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_C)
    integer(c_unsigned), parameter, public :: SDLK_KP_D                   = int(z'400000bf', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_D)
    integer(c_unsigned), parameter, public :: SDLK_KP_E                   = int(z'400000c0', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_E)
    integer(c_unsigned), parameter, public :: SDLK_KP_F                   = int(z'400000c1', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_F)
    integer(c_unsigned), parameter, public :: SDLK_KP_XOR                 = int(z'400000c2', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_XOR)
    integer(c_unsigned), parameter, public :: SDLK_KP_POWER               = int(z'400000c3', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_POWER)
    integer(c_unsigned), parameter, public :: SDLK_KP_PERCENT             = int(z'400000c4', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PERCENT)
    integer(c_unsigned), parameter, public :: SDLK_KP_LESS                = int(z'400000c5', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LESS)
    integer(c_unsigned), parameter, public :: SDLK_KP_GREATER             = int(z'400000c6', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_GREATER)
    integer(c_unsigned), parameter, public :: SDLK_KP_AMPERSAND           = int(z'400000c7', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_AMPERSAND)
    integer(c_unsigned), parameter, public :: SDLK_KP_DBLAMPERSAND        = int(z'400000c8', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DBLAMPERSAND)
    integer(c_unsigned), parameter, public :: SDLK_KP_VERTICALBAR         = int(z'400000c9', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_VERTICALBAR)
    integer(c_unsigned), parameter, public :: SDLK_KP_DBLVERTICALBAR      = int(z'400000ca', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DBLVERTICALBAR)
    integer(c_unsigned), parameter, public :: SDLK_KP_COLON               = int(z'400000cb', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_COLON)
    integer(c_unsigned), parameter, public :: SDLK_KP_HASH                = int(z'400000cc', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_HASH)
    integer(c_unsigned), parameter, public :: SDLK_KP_SPACE               = int(z'400000cd', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_SPACE)
    integer(c_unsigned), parameter, public :: SDLK_KP_AT                  = int(z'400000ce', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_AT)
    integer(c_unsigned), parameter, public :: SDLK_KP_EXCLAM              = int(z'400000cf', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EXCLAM)
    integer(c_unsigned), parameter, public :: SDLK_KP_MEMSTORE            = int(z'400000d0', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMSTORE)
    integer(c_unsigned), parameter, public :: SDLK_KP_MEMRECALL           = int(z'400000d1', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMRECALL)
    integer(c_unsigned), parameter, public :: SDLK_KP_MEMCLEAR            = int(z'400000d2', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMCLEAR)
    integer(c_unsigned), parameter, public :: SDLK_KP_MEMADD              = int(z'400000d3', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMADD)
    integer(c_unsigned), parameter, public :: SDLK_KP_MEMSUBTRACT         = int(z'400000d4', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMSUBTRACT)
    integer(c_unsigned), parameter, public :: SDLK_KP_MEMMULTIPLY         = int(z'400000d5', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMMULTIPLY)
    integer(c_unsigned), parameter, public :: SDLK_KP_MEMDIVIDE           = int(z'400000d6', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMDIVIDE)
    integer(c_unsigned), parameter, public :: SDLK_KP_PLUSMINUS           = int(z'400000d7', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PLUSMINUS)
    integer(c_unsigned), parameter, public :: SDLK_KP_CLEAR               = int(z'400000d8', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_CLEAR)
    integer(c_unsigned), parameter, public :: SDLK_KP_CLEARENTRY          = int(z'400000d9', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_CLEARENTRY)
    integer(c_unsigned), parameter, public :: SDLK_KP_BINARY              = int(z'400000da', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_BINARY)
    integer(c_unsigned), parameter, public :: SDLK_KP_OCTAL               = int(z'400000db', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_OCTAL)
    integer(c_unsigned), parameter, public :: SDLK_KP_DECIMAL             = int(z'400000dc', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DECIMAL)
    integer(c_unsigned), parameter, public :: SDLK_KP_HEXADECIMAL         = int(z'400000dd', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_HEXADECIMAL)
    integer(c_unsigned), parameter, public :: SDLK_LCTRL                  = int(z'400000e0', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LCTRL)
    integer(c_unsigned), parameter, public :: SDLK_LSHIFT                 = int(z'400000e1', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LSHIFT)
    integer(c_unsigned), parameter, public :: SDLK_LALT                   = int(z'400000e2', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LALT)
    integer(c_unsigned), parameter, public :: SDLK_LGUI                   = int(z'400000e3', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LGUI)
    integer(c_unsigned), parameter, public :: SDLK_RCTRL                  = int(z'400000e4', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RCTRL)
    integer(c_unsigned), parameter, public :: SDLK_RSHIFT                 = int(z'400000e5', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RSHIFT)
    integer(c_unsigned), parameter, public :: SDLK_RALT                   = int(z'400000e6', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RALT)
    integer(c_unsigned), parameter, public :: SDLK_RGUI                   = int(z'400000e7', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RGUI)
    integer(c_unsigned), parameter, public :: SDLK_MODE                   = int(z'40000101', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MODE)
    integer(c_unsigned), parameter, public :: SDLK_SLEEP                  = int(z'40000102', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SLEEP)
    integer(c_unsigned), parameter, public :: SDLK_WAKE                   = int(z'40000103', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_WAKE)
    integer(c_unsigned), parameter, public :: SDLK_CHANNEL_INCREMENT      = int(z'40000104', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CHANNEL_INCREMENT)
    integer(c_unsigned), parameter, public :: SDLK_CHANNEL_DECREMENT      = int(z'40000105', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CHANNEL_DECREMENT)
    integer(c_unsigned), parameter, public :: SDLK_MEDIA_PLAY             = int(z'40000106', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PLAY)
    integer(c_unsigned), parameter, public :: SDLK_MEDIA_PAUSE            = int(z'40000107', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PAUSE)
    integer(c_unsigned), parameter, public :: SDLK_MEDIA_RECORD           = int(z'40000108', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_RECORD)
    integer(c_unsigned), parameter, public :: SDLK_MEDIA_FAST_FORWARD     = int(z'40000109', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_FAST_FORWARD)
    integer(c_unsigned), parameter, public :: SDLK_MEDIA_REWIND           = int(z'4000010a', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_REWIND)
    integer(c_unsigned), parameter, public :: SDLK_MEDIA_NEXT_TRACK       = int(z'4000010b', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_NEXT_TRACK)
    integer(c_unsigned), parameter, public :: SDLK_MEDIA_PREVIOUS_TRACK   = int(z'4000010c', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PREVIOUS_TRACK)
    integer(c_unsigned), parameter, public :: SDLK_MEDIA_STOP             = int(z'4000010d', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_STOP)
    integer(c_unsigned), parameter, public :: SDLK_MEDIA_EJECT            = int(z'4000010e', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_EJECT)
    integer(c_unsigned), parameter, public :: SDLK_MEDIA_PLAY_PAUSE       = int(z'4000010f', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PLAY_PAUSE)
    integer(c_unsigned), parameter, public :: SDLK_MEDIA_SELECT           = int(z'40000110', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_SELECT)
    integer(c_unsigned), parameter, public :: SDLK_AC_NEW                 = int(z'40000111', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_NEW)
    integer(c_unsigned), parameter, public :: SDLK_AC_OPEN                = int(z'40000112', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_OPEN)
    integer(c_unsigned), parameter, public :: SDLK_AC_CLOSE               = int(z'40000113', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_CLOSE)
    integer(c_unsigned), parameter, public :: SDLK_AC_EXIT                = int(z'40000114', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_EXIT)
    integer(c_unsigned), parameter, public :: SDLK_AC_SAVE                = int(z'40000115', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_SAVE)
    integer(c_unsigned), parameter, public :: SDLK_AC_PRINT               = int(z'40000116', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_PRINT)
    integer(c_unsigned), parameter, public :: SDLK_AC_PROPERTIES          = int(z'40000117', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_PROPERTIES)
    integer(c_unsigned), parameter, public :: SDLK_AC_SEARCH              = int(z'40000118', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_SEARCH)
    integer(c_unsigned), parameter, public :: SDLK_AC_HOME                = int(z'40000119', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_HOME)
    integer(c_unsigned), parameter, public :: SDLK_AC_BACK                = int(z'4000011a', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_BACK)
    integer(c_unsigned), parameter, public :: SDLK_AC_FORWARD             = int(z'4000011b', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_FORWARD)
    integer(c_unsigned), parameter, public :: SDLK_AC_STOP                = int(z'4000011c', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_STOP)
    integer(c_unsigned), parameter, public :: SDLK_AC_REFRESH             = int(z'4000011d', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_REFRESH)
    integer(c_unsigned), parameter, public :: SDLK_AC_BOOKMARKS           = int(z'4000011e', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_BOOKMARKS)
    integer(c_unsigned), parameter, public :: SDLK_SOFTLEFT               = int(z'4000011f', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SOFTLEFT)
    integer(c_unsigned), parameter, public :: SDLK_SOFTRIGHT              = int(z'40000120', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SOFTRIGHT)
    integer(c_unsigned), parameter, public :: SDLK_CALL                   = int(z'40000121', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CALL)
    integer(c_unsigned), parameter, public :: SDLK_ENDCALL                = int(z'40000122', c_unsigned) ! SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_ENDCALL)
    integer(c_unsigned), parameter, public :: SDLK_LEFT_TAB               = int(z'20000001', c_unsigned) ! Extended key Left Tab.
    integer(c_unsigned), parameter, public :: SDLK_LEVEL5_SHIFT           = int(z'20000002', c_unsigned) ! Extended key Level 5 Shift.
    integer(c_unsigned), parameter, public :: SDLK_MULTI_KEY_COMPOSE      = int(z'20000003', c_unsigned) ! Extended key Multi-key Compose.
    integer(c_unsigned), parameter, public :: SDLK_LMETA                  = int(z'20000004', c_unsigned) ! Extended key Left Meta.
    integer(c_unsigned), parameter, public :: SDLK_RMETA                  = int(z'20000005', c_unsigned) ! Extended key Right Meta.
    integer(c_unsigned), parameter, public :: SDLK_LHYPER                 = int(z'20000006', c_unsigned) ! Extended key Left Hyper.
    integer(c_unsigned), parameter, public :: SDLK_RHYPER                 = int(z'20000007', c_unsigned) ! Extended key Right Hyper.

    integer(c_unsigned), parameter, public :: SDL_KMOD_NONE   = int(z'0000', c_unsigned)              ! No modifier is applicable.
    integer(c_unsigned), parameter, public :: SDL_KMOD_LSHIFT = int(z'0001', c_unsigned)              ! The left Shift key is down.
    integer(c_unsigned), parameter, public :: SDL_KMOD_RSHIFT = int(z'0002', c_unsigned)              ! The right Shift key is down.
    integer(c_unsigned), parameter, public :: SDL_KMOD_LEVEL5 = int(z'0004', c_unsigned)              ! The Level 5 Shift key is down.
    integer(c_unsigned), parameter, public :: SDL_KMOD_LCTRL  = int(z'0040', c_unsigned)              ! The left Ctrl (Control) key is down.
    integer(c_unsigned), parameter, public :: SDL_KMOD_RCTRL  = int(z'0080', c_unsigned)              ! The right Ctrl (Control) key is down.
    integer(c_unsigned), parameter, public :: SDL_KMOD_LALT   = int(z'0100', c_unsigned)              ! The left Alt key is down.
    integer(c_unsigned), parameter, public :: SDL_KMOD_RALT   = int(z'0200', c_unsigned)              ! The right Alt key is down.
    integer(c_unsigned), parameter, public :: SDL_KMOD_LGUI   = int(z'0400', c_unsigned)              ! The left GUI key (often the Windows key) is down.
    integer(c_unsigned), parameter, public :: SDL_KMOD_RGUI   = int(z'0800', c_unsigned)              ! The right GUI key (often the Windows key) is down.
    integer(c_unsigned), parameter, public :: SDL_KMOD_NUM    = int(z'1000', c_unsigned)              ! The Num Lock key (may be located on an extended keypad) is down.
    integer(c_unsigned), parameter, public :: SDL_KMOD_CAPS   = int(z'2000', c_unsigned)              ! The Caps Lock key is down.
    integer(c_unsigned), parameter, public :: SDL_KMOD_MODE   = int(z'4000', c_unsigned)              ! The !AltGr key is down.
    integer(c_unsigned), parameter, public :: SDL_KMOD_SCROLL = int(z'8000', c_unsigned)              ! The Scroll Lock key is down.
    integer(c_unsigned), parameter, public :: SDL_KMOD_CTRL   = ior(SDL_KMOD_LCTRL,  SDL_KMOD_RCTRL)  ! Any Ctrl key is down.
    integer(c_unsigned), parameter, public :: SDL_KMOD_SHIFT  = ior(SDL_KMOD_LSHIFT, SDL_KMOD_RSHIFT) ! Any Shift key is down.
    integer(c_unsigned), parameter, public :: SDL_KMOD_ALT    = ior(SDL_KMOD_LALT,   SDL_KMOD_RALT)   ! Any Alt key is down.
    integer(c_unsigned), parameter, public :: SDL_KMOD_GUI    = ior(SDL_KMOD_LGUI,   SDL_KMOD_RGUI)   ! Any GUI key is down.
end module sdl3_keycode
